apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: backend-ns
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: docker.io/khalidtarek7/nagato
          ports:
            - containerPort: 3000